# Generated by Django 6.0.6 on 2026-09-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='ID студента')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Студент (whitelist)',
                'verbose_name_plural': 'Студенты (whitelist)',
                'ordering': ['student_id'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID студента'),
        ),
    ]
